services:
  #  -----------------------------------------------------
  #  Infrastructure Service
  #  -----------------------------------------------------
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - gyp-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - gyp-net

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - gyp-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8089:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - gyp-net

  mail-dev:
    image: maildev/maildev
    container_name: mail-dev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - gyp-net

  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=12345
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./redis_data:/bitnami/redis/data
    restart: unless-stopped
    networks:
      - gyp-net

  mysql:
    image: mysql:8.0.21
    container_name: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "13306:3306"
    networks:
      - gyp-net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
    networks:
      - gyp-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: 12345
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "18080:8080"
    command: start-dev
    depends_on:
      - mysql
    networks:
      - gyp-net

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gyp-net

  #  -----------------------------------------------------
  #  Internal Service
  #  -----------------------------------------------------
  discovery-service:
    build: ../../discovery-service
    container_name: discovery-service
    ports:
      - "9761:9761"
    networks:
      - gyp-net

  api-gateway:
    build: ../../api-gateway
    container_name: api-gateway
    ports:
      - "9999:9999"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:9761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=false
      - EUREKA_INSTANCE_HOSTNAME=api-gateway
    depends_on:
      - discovery-service
    networks:
      - gyp-net

  auth-service:
    build: ../../auth-service
    container_name: auth-service
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - ../../.env
    depends_on:
      - discovery-service
      - mysql
      - kafka
    networks:
      - gyp-net

  bff-service:
    build: ../../bff-service
    container_name: bff-service
    ports:
      - "9010:9010"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - ../../.env
    depends_on:
      - discovery-service
    networks:
      - gyp-net

  event-service:
    build: ../../event-service
    container_name: event-service
    ports:
      - "9001:9001"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - ../../.env
    depends_on:
      - discovery-service
      - mysql
      - kafka
    networks:
      - gyp-net

  ticket-service:
    build: ../../ticket-service
    container_name: ticket-service
    ports:
      - "9002:9002"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - ../../.env
    depends_on:
      - discovery-service
      - mysql
    networks:
      - gyp-net

  salechannel-service:
    build: ../../salechannel-service
    container_name: salechannel-service
    ports:
      - "9004:9004"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - ../../.env
    depends_on:
      - discovery-service
      - mysql
      - kafka
    networks:
      - gyp-net

  order-service:
    build: ../../order-service
    container_name: order-service
    ports:
      - "9003:9003"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - ../../.env
    depends_on:
      - discovery-service
      - mysql
      - kafka
      - redis
    networks:
      - gyp-net

  web-ui:
    build: ../../frontend/gyp-core-ui
    container_name: web-ui
    ports:
      - "3000:3000"
    environment:
      - VITE_API_GATEWAY_URL=http://localhost:9999
      - VITE_RESPONSE_URL=http://localhost:3000/user-account
      - VITE_REDIRECT_URL=http://localhost:3000/callback
      - VITE_CLIENT_ID=gyp-core-ui
    depends_on:
      - api-gateway
    networks:
      - gyp-net

networks:
  gyp-net:
    driver: bridge
