services:
  #  -----------------------------------------------------
  #  Infrastructure Service
  #  -----------------------------------------------------
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - gyp-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - gyp-net

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - gyp-net

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8089:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - gyp-net

  mail-dev:
    image: maildev/maildev
    container_name: mail-dev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - gyp-net

  redis:
    image: bitnami/redis:8.0.0
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 12345
    restart: unless-stopped
    networks:
      - gyp-net

  mysql:
    image: mysql:8.0.21
    container_name: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - "13306:3306"
    networks:
      - gyp-net

  #  -----------------------------------------------------
  #  Internal Service
  #  -----------------------------------------------------
  discovery-service:
    build: ../../discovery-service
    container_name: discovery-service
    ports:
      - "9761:9761"
    networks:
      - gyp-net

  api-gateway:
    build: ../../api-gateway
    container_name: api-gateway
    ports:
      - "9999:9999"
    depends_on:
      - discovery-service
    networks:
      - gyp-net

  auth-service:
    build: ../../auth-service
    container_name: auth-service
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - discovery-service
      - mysql
      - kafka
    networks:
      - gyp-net

  event-service:
    build: ../../event-service
    container_name: event-service
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/event_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - discovery-service
      - mysql
      - kafka
    networks:
      - gyp-net

  ticket-service:
    build: ../../ticket-service
    container_name: ticket-service
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ticket_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - discovery-service
      - mysql
    networks:
      - gyp-net

#  salechannel-service:
#    build: ../../salechannel-service
#    container_name: salechannel-service
#    ports:
#      - "9002:9002"
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/salechannel_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=12345
#      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#    depends_on:
#      - discovery-service
#      - mysql
#      - kafka
#    networks:
#      - gyp-net

networks:
  gyp-net:
    driver: bridge
