version: '1.0'

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - gyp-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - gyp-net

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - gyp-net

  kafka-ui:
    container_name: kafka-ui
    image: redpandadata/console:v3.1.0
    ports:
      - "9090:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    networks:
      - gyp-net

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - gyp-net

  mysql:
    image: mysql:8.0.21
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - 13306:3306
    networks:
      - gyp-net

  discovery-service:
    build: ./discovery-service
    ports:
      - "9761:9761"
    networks:
      - gyp-net

  auth-service:
    build: ./auth-service
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth_service?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - discovery-service
      - mysql
    networks:
      - gyp-net

  event-service:
    build: ./event-service
    ports:
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/event-service?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - discovery-service
      - mysql
    networks:
      - gyp-net

networks:
  gyp-net:
    driver: bridge