# ===============================
# notification-service Prod Configuration
# ===============================

# SMTP (production mail server)
spring:
  mail:
    host: mail-dev
    port: 1025
    username: no-reply@gmail.com
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
