spring:
  mail:
    host: mail-dev
    port: 1025
    username: no-reply@gmail.com
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: ticket-service

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
