# ===============================
# Server Configuration
# ===============================
spring.application.name=api-gateway
server.port=9999

# ===============================
# JWT Configuration
# ===============================
jwt.secret.token=kZvFECgzEsX5bhcOY/SUJo9JGp1quQNeKeinebiXO9ImHNfIROwa7+QnqhSLOa6K

# ===============================
# Eureka Discovery
# ===============================
eureka.client.service-url.defaultZone=http://localhost:9761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ===============================
# Spring Cloud Gateway
# ===============================
spring.cloud.gateway.discovery.locator.enabled=true

# Global CORS Configuration
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origin-patterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[3]=DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods[4]=OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600

# Default Filters
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# -------- auth-service Route --------
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auths/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auths(?<segment>/?.*), $\{segment}

# -------- event-service Route --------
spring.cloud.gateway.routes[1].id=event-service
spring.cloud.gateway.routes[1].uri=lb://EVENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/events/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/events(?<segment>/?.*), $\{segment}

# -------- ticket-service Route --------
spring.cloud.gateway.routes[2].id=ticket-service
spring.cloud.gateway.routes[2].uri=lb://TICKET-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/tickets/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/tickets(?<segment>/?.*), $\{segment}

# -------- sale-channel-service Route --------
spring.cloud.gateway.routes[3].id=salechannel-service
spring.cloud.gateway.routes[3].uri=lb://SALECHANNEL-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/salechannels/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/salechannels(?<segment>/?.*), $\{segment}

# -------- order-service Route --------
spring.cloud.gateway.routes[4].id=order-service
spring.cloud.gateway.routes[4].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/orders/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/orders(?<segment>/?.*), $\{segment}

# -------- notification-service Route --------
spring.cloud.gateway.routes[5].id=notification-service
spring.cloud.gateway.routes[5].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/notifications/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/notifications(?<segment>/?.*), $\{segment}

# ===============================
# Logging Configuration
# ===============================
logging.level.root=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.cloud.gateway.filter.factory.RewritePathGatewayFilterFactory=DEBUG

# ===============================
# Swagger Configuration
# ===============================
springdoc.api-docs.groups.enabled=true

# -------- auth-service swagger Route --------
springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/auths/v3/api-docs

# -------- event-service swagger Route --------
springdoc.swagger-ui.urls[1].name=event-service
springdoc.swagger-ui.urls[1].url=/events/v3/api-docs

# -------- ticket-service swagger Route --------
springdoc.swagger-ui.urls[2].name=ticket-service
springdoc.swagger-ui.urls[2].url=/tickets/v3/api-docs

# -------- sale-channel-service swagger Route --------
springdoc.swagger-ui.urls[3].name=salechannel-service
springdoc.swagger-ui.urls[3].url=/salechannels/v3/api-docs

# -------- order-service swagger Route --------
springdoc.swagger-ui.urls[4].name=order-service
springdoc.swagger-ui.urls[4].url=/orders/v3/api-docs

# -------- notification-service swagger Route --------
springdoc.swagger-ui.urls[5].name=notification-service
springdoc.swagger-ui.urls[5].url=/notifications/v3/api-docs
