# ===============================
# Application & Server Config
# ===============================
spring.application.name=api-gateway
spring.profiles.active=@spring-boot.run.profiles@

# ===============================
# JWT Configuration
# ===============================
jwt.secret.token=kZvFECgzEsX5bhcOY/SUJo9JGp1quQNeKeinebiXO9ImHNfIROwa7+QnqhSLOa6K

# ===============================
# Spring Cloud Gateway
# ===============================
spring.cloud.gateway.discovery.locator.enabled=true

# -------- auth-service Route --------
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/auths/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auths(?<segment>/?.*), $\{segment}

# -------- event-service Route --------
spring.cloud.gateway.routes[1].id=event-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/events/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/events(?<segment>/?.*), $\{segment}

# -------- notification-service Route --------
spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/notifications/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/notifications(?<segment>/?.*), $\{segment}