# ===============================
# Application & Server Config
# ===============================
spring.application.name=api-gateway
server.port=8888
spring.main.web-application-type=reactive
app.api.prefix=/api/v1

# ===============================
# JWT Configuration
# ===============================
jwt.secret.token=kZvFECgzEsX5bhcOY/SUJo9JGp1quQNeKeinebiXO9ImHNfIROwa7+QnqhSLOa6K

# ===============================
# Eureka Discovery
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ===============================
# Spring Cloud Gateway
# ===============================
spring.cloud.gateway.discovery.locator.enabled=true

# -------- auth-service Route --------
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auths/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auths(?<segment>/?.*), $\{segment}

# -------- event-service Route --------
spring.cloud.gateway.routes[1].id=event-service
spring.cloud.gateway.routes[1].uri=lb://EVENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/events/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/events(?<segment>/?.*), $\{segment}

# -------- movie-service Route --------
spring.cloud.gateway.routes[2].id=movie-service
spring.cloud.gateway.routes[2].uri=lb://MOVIE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/movies/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/movies(?<segment>/?.*), $\{segment}

# -------- theater-service Route --------
spring.cloud.gateway.routes[3].id=theater-service
spring.cloud.gateway.routes[3].uri=lb://THEATER-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/theaters/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/theaters(?<segment>/?.*), $\{segment}

# -------- notification-service Route --------
spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/notifications/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/notifications(?<segment>/?.*), $\{segment}