# ===============================
# Shared Configuration (All Services, All Profiles)
# ===============================

spring:
  # AOP
  aop:
    proxy-target-class: true

  # JPA Common
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  # Flyway Common
  flyway:
    baseline-on-migrate: true

# ===============================
# Actuator / Metrics
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      service: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
        spring.cloud.gateway.requests: true
