# ===============================
# auth-service Configuration
# ===============================
server:
  port: 9000

jwt:
  secret:
    token: ${JWT_SECRET_TOKEN}

# ===============================
# OAuth2 Client Configuration For Google
# ===============================
customer:
  frontend:
    base-url: ${CUSTOMER_FRONTEND_BASE_URL:http://localhost:3000/gyp/}
    login-url: ${CUSTOMER_FRONTEND_LOGIN_URL:${customer.frontend.base-url}/login}
    oauth2-callback-url: ${CUSTOMER_FRONTEND_OAUTH2_CALLBACK_URL:${customer.frontend.base-url}/oauth2/callback}

spring:
  security:
    oauth2:
      client:
        registration:
          google-customer:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,email,profile
            redirect-uri: ${API_GATEWAY_URL:http://localhost:9999}/auths/customer/oauth2/callback/google-customer
            authorization-grant-type: authorization_code
            client-name: Google
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope: openid
            redirect-uri: ${API_GATEWAY_URL:http://localhost:9999}/auths/oidc/oauth2/callback/keycloak
            authorization-grant-type: authorization_code
        provider:
          google-customer:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            issuer-uri: https://accounts.google.com
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  kafka:
    consumer:
      group-id: auth-service-group

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: auth_service

# Service-specific database schema
service:
  database:
    schema: auth_service
