spring.cloud.config.override-system-properties=false

eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

name.value=ticket-booking-service

management.tracing.sampling.probability=1.0