server.port=8888

app.api-prefix=/api/v1

spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.discovery.routes[0].id=auth-service
spring.cloud.gateway.discovery.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.discovery.routes[0].predicates[0]=Path=/auths/**

spring.cloud.gateway.discovery.routes[1].id=booking-service
spring.cloud.gateway.discovery.routes[1].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.discovery.routes[1].predicates[0]=Path=/bookings/**

spring.cloud.gateway.discovery.routes[2].id=movie-service
spring.cloud.gateway.discovery.routes[2].uri=lb://MOVIE-SERVICE
spring.cloud.gateway.discovery.routes[2].predicates[0]=Path=/movies/**

spring.cloud.gateway.discovery.routes[3].id=theater-service
spring.cloud.gateway.discovery.routes[3].uri=lb://THEATER-SERVICE
spring.cloud.gateway.discovery.routes[3].predicates[0]=Path=/theaters/**

spring.cloud.gateway.discovery.routes[4].id=notification-service
spring.cloud.gateway.discovery.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.discovery.routes[4].predicates[0]=Path=/notifications/**