server:
  port: 9002

jwt:
  secret:
    token: ${JWT_SECRET_TOKEN}

spring:
  kafka:
    consumer:
      group-id: ticket-service-group

  jpa:
    hibernate:
      ddl-auto: update

service:
  database:
    schema: ticket_service
