spring:
  application:
    name: bff-service
  config:
    import: optional:classpath:observability/common-actuator.properties

server:
  port: 9010

# ===============================
# Eureka Discovery
# ===============================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
