# ===============================
# Server Configuration
# ===============================
server.port=9003
spring.application.name=order-service

# ===============================
# AOP
# ===============================
spring.aop.proxy-target-class=true

# ===============================
# JWT Configuration
# ===============================
jwt.secret.token=${JWT_SECRET_TOKEN}

# ===============================
# Database Configuration
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:13306/order_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# ===============================
# Flyway Migration
# ===============================
spring.flyway.enabled=true
spring.flyway.url=jdbc:mysql://localhost:13306/order_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.flyway.user=root
spring.flyway.password=12345
spring.flyway.baseline-on-migrate=true

# ===============================
# Kafka Configuration
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# Producer settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer settings
spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# ===============================
# Eureka Discovery
# ===============================;
eureka.client.service-url.defaultZone=http://localhost:9761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ===============================
# MOMO Configuration
# ===============================
momo.partner-code=${MOMO_PARTNER_CODE}
momo.access-key=${MOMO_ACCESS_KEY}
momo.secret-key=${MOMO_SECRET_KEY}
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.return-url=http://localhost:9999/orders/payments/paymentinfo
momo.notify-url=http://localhost:9999/orders/payments/paymentnotify
momo.frontend-success-url=http://localhost:3000/gyp/payment/success
momo.frontend-failure-url=http://localhost:3000/gyp/payment/failure

# ===============================
# MINIO Configuration
# ===============================
minio.enabled=false

# ===============================
# Redis Configuration
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=12345
spring.data.redis.database=0