CREATE DATABASE IF NOT EXISTS auth_service;
CREATE DATABASE IF NOT EXISTS event_service;
CREATE DATABASE IF NOT EXISTS ticket_service;
CREATE DATABASE IF NOT EXISTS order_service;
CREATE DATABASE IF NOT EXISTS salechannel_service;
CREATE DATABASE IF NOT EXISTS keycloak;