spring:
  application:
    name: ticket-service
  config:
    import: optional:configserver:http://localhost:9006
  cloud:
    config:
      fail-fast: false
      name: ticket-service,database,cache,kafka
